// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { PlatformCancelApplicationTransferData, PlatformCancelApplicationTransferErrors, PlatformCancelApplicationTransferResponses, PlatformCreateApplicationData, PlatformCreateApplicationErrors, PlatformCreateApplicationResponses, PlatformCreateApplicationTransferData, PlatformCreateApplicationTransferErrors, PlatformCreateApplicationTransferResponses, PlatformDeleteApplicationData, PlatformDeleteApplicationErrors, PlatformDeleteApplicationResponses, PlatformGetApplicationData, PlatformGetApplicationDomainData, PlatformGetApplicationDomainErrors, PlatformGetApplicationDomainResponses, PlatformGetApplicationDomainStatusData, PlatformGetApplicationDomainStatusErrors, PlatformGetApplicationDomainStatusResponses, PlatformGetApplicationErrors, PlatformGetApplicationResponses, PlatformGetApplicationTransferData, PlatformGetApplicationTransferErrors, PlatformGetApplicationTransferResponses, PlatformListApplicationsData, PlatformListApplicationsErrors, PlatformListApplicationsResponses, PlatformTriggerDnsCheckData, PlatformTriggerDnsCheckErrors, PlatformTriggerDnsCheckResponses, PlatformUpdateApplicationData, PlatformUpdateApplicationDomainData, PlatformUpdateApplicationDomainErrors, PlatformUpdateApplicationDomainResponses, PlatformUpdateApplicationErrors, PlatformUpdateApplicationResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List applications
 *
 * List applications.
 *
 */
export const platformListApplications = <ThrowOnError extends boolean = false>(options?: Options<PlatformListApplicationsData, ThrowOnError>) => (options?.client ?? client).get<PlatformListApplicationsResponses, PlatformListApplicationsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/platform/applications',
    ...options
});

/**
 * Create an application
 *
 * Create a new application.
 *
 */
export const platformCreateApplication = <ThrowOnError extends boolean = false>(options: Options<PlatformCreateApplicationData, ThrowOnError>) => (options.client ?? client).post<PlatformCreateApplicationResponses, PlatformCreateApplicationErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/platform/applications',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an application
 *
 * Delete an application.
 *
 */
export const platformDeleteApplication = <ThrowOnError extends boolean = false>(options: Options<PlatformDeleteApplicationData, ThrowOnError>) => (options.client ?? client).delete<PlatformDeleteApplicationResponses, PlatformDeleteApplicationErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/platform/applications/{applicationID}',
    ...options
});

/**
 * Get an application
 *
 * Get application details.
 *
 */
export const platformGetApplication = <ThrowOnError extends boolean = false>(options: Options<PlatformGetApplicationData, ThrowOnError>) => (options.client ?? client).get<PlatformGetApplicationResponses, PlatformGetApplicationErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/platform/applications/{applicationID}',
    ...options
});

/**
 * Update an application
 *
 * Update an application.
 *
 */
export const platformUpdateApplication = <ThrowOnError extends boolean = false>(options: Options<PlatformUpdateApplicationData, ThrowOnError>) => (options.client ?? client).patch<PlatformUpdateApplicationResponses, PlatformUpdateApplicationErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/platform/applications/{applicationID}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update application domain
 *
 * Update the production domain for an application.
 *
 */
export const platformUpdateApplicationDomain = <ThrowOnError extends boolean = false>(options: Options<PlatformUpdateApplicationDomainData, ThrowOnError>) => (options.client ?? client).patch<PlatformUpdateApplicationDomainResponses, PlatformUpdateApplicationDomainErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/platform/applications/{applicationID}/domain',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get application domain
 *
 * Get domain information for an application.
 *
 */
export const platformGetApplicationDomain = <ThrowOnError extends boolean = false>(options: Options<PlatformGetApplicationDomainData, ThrowOnError>) => (options.client ?? client).get<PlatformGetApplicationDomainResponses, PlatformGetApplicationDomainErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/platform/applications/{applicationID}/domains/{domainIDOrName}',
    ...options
});

/**
 * Get application domain status
 *
 * Get the status of a domain for an application.
 *
 */
export const platformGetApplicationDomainStatus = <ThrowOnError extends boolean = false>(options: Options<PlatformGetApplicationDomainStatusData, ThrowOnError>) => (options.client ?? client).get<PlatformGetApplicationDomainStatusResponses, PlatformGetApplicationDomainStatusErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/platform/applications/{applicationID}/domains/{domainIDOrName}/status',
    ...options
});

/**
 * Trigger DNS check
 *
 * Triggers a DNS check for a domain and returns the current domain status.
 *
 * This endpoint ensures that at most one DNS check job is in-flight at any time.
 * If a check is already running or was recently performed, a 409 Conflict is returned.
 *
 * Use this endpoint to trigger a new DNS verification check after configuring DNS records.
 *
 */
export const platformTriggerDnsCheck = <ThrowOnError extends boolean = false>(options: Options<PlatformTriggerDnsCheckData, ThrowOnError>) => (options.client ?? client).post<PlatformTriggerDnsCheckResponses, PlatformTriggerDnsCheckErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/platform/applications/{applicationID}/domains/{domainIDOrName}/dns_check',
    ...options
});

/**
 * Create an application transfer
 *
 * Create a new transfer request for an application. This initiates the process of
 * transferring ownership of the application to another workspace.
 *
 * Only one pending transfer can exist for an application at a time. The transfer
 * will expire after 24 hours if not completed.
 *
 */
export const platformCreateApplicationTransfer = <ThrowOnError extends boolean = false>(options: Options<PlatformCreateApplicationTransferData, ThrowOnError>) => (options.client ?? client).post<PlatformCreateApplicationTransferResponses, PlatformCreateApplicationTransferErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/platform/applications/{applicationID}/transfers',
    ...options
});

/**
 * Cancel an application transfer
 *
 * Cancel an existing application transfer. Only transfers in 'pending' status can be canceled.
 *
 */
export const platformCancelApplicationTransfer = <ThrowOnError extends boolean = false>(options: Options<PlatformCancelApplicationTransferData, ThrowOnError>) => (options.client ?? client).delete<PlatformCancelApplicationTransferResponses, PlatformCancelApplicationTransferErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/platform/applications/{applicationID}/transfers/{transferID}',
    ...options
});

/**
 * Get an application transfer
 *
 * Retrieve details of an application transfer by its ID.
 *
 */
export const platformGetApplicationTransfer = <ThrowOnError extends boolean = false>(options: Options<PlatformGetApplicationTransferData, ThrowOnError>) => (options.client ?? client).get<PlatformGetApplicationTransferResponses, PlatformGetApplicationTransferErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/platform/applications/{applicationID}/transfers/{transferID}',
    ...options
});
