// This file is auto-generated by @hey-api/openapi-ts
import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  PlatformBanUserData,
  PlatformBanUserErrors,
  PlatformBanUserResponses,
  PlatformCancelApplicationTransferData,
  PlatformCancelApplicationTransferErrors,
  PlatformCancelApplicationTransferResponses,
  PlatformCreateApplicationData,
  PlatformCreateApplicationDomainData,
  PlatformCreateApplicationDomainErrors,
  PlatformCreateApplicationDomainResponses,
  PlatformCreateApplicationErrors,
  PlatformCreateApplicationResponses,
  PlatformCreateApplicationTransferData,
  PlatformCreateApplicationTransferErrors,
  PlatformCreateApplicationTransferResponses,
  PlatformCreateJwtTemplateData,
  PlatformCreateJwtTemplateErrors,
  PlatformCreateJwtTemplateResponses,
  PlatformCreateRedirectUrlData,
  PlatformCreateRedirectUrlErrors,
  PlatformCreateRedirectUrlResponses,
  PlatformDeleteApplicationData,
  PlatformDeleteApplicationDomainData,
  PlatformDeleteApplicationDomainErrors,
  PlatformDeleteApplicationDomainResponses,
  PlatformDeleteApplicationErrors,
  PlatformDeleteApplicationFaviconData,
  PlatformDeleteApplicationFaviconErrors,
  PlatformDeleteApplicationFaviconResponses,
  PlatformDeleteApplicationLogoData,
  PlatformDeleteApplicationLogoErrors,
  PlatformDeleteApplicationLogoResponses,
  PlatformDeleteApplicationResponses,
  PlatformDeleteJwtTemplateData,
  PlatformDeleteJwtTemplateErrors,
  PlatformDeleteJwtTemplateResponses,
  PlatformDeleteRedirectUrlData,
  PlatformDeleteRedirectUrlErrors,
  PlatformDeleteRedirectUrlResponses,
  PlatformGetApplicationData,
  PlatformGetApplicationDomainData,
  PlatformGetApplicationDomainErrors,
  PlatformGetApplicationDomainResponses,
  PlatformGetApplicationDomainStatusData,
  PlatformGetApplicationDomainStatusErrors,
  PlatformGetApplicationDomainStatusResponses,
  PlatformGetApplicationErrors,
  PlatformGetApplicationResponses,
  PlatformGetApplicationTransferData,
  PlatformGetApplicationTransferErrors,
  PlatformGetApplicationTransferResponses,
  PlatformGetConfigData,
  PlatformGetConfigErrors,
  PlatformGetConfigResponses,
  PlatformGetConfigSchemaData,
  PlatformGetConfigSchemaErrors,
  PlatformGetConfigSchemaResponses,
  PlatformGetInstanceUsageData,
  PlatformGetInstanceUsageErrors,
  PlatformGetInstanceUsageResponses,
  PlatformGetJwtTemplateData,
  PlatformGetJwtTemplateErrors,
  PlatformGetJwtTemplateResponses,
  PlatformGetRedirectUrlData,
  PlatformGetRedirectUrlErrors,
  PlatformGetRedirectUrlResponses,
  PlatformListApplicationDomainsData,
  PlatformListApplicationDomainsErrors,
  PlatformListApplicationDomainsResponses,
  PlatformListApplicationsData,
  PlatformListApplicationsErrors,
  PlatformListApplicationsResponses,
  PlatformListApplicationTransfersData,
  PlatformListApplicationTransfersErrors,
  PlatformListApplicationTransfersResponses,
  PlatformListInstanceUsersData,
  PlatformListInstanceUsersErrors,
  PlatformListInstanceUsersResponses,
  PlatformListJwtTemplatesData,
  PlatformListJwtTemplatesErrors,
  PlatformListJwtTemplatesResponses,
  PlatformListRedirectUrlsData,
  PlatformListRedirectUrlsErrors,
  PlatformListRedirectUrlsResponses,
  PlatformPatchConfigData,
  PlatformPatchConfigErrors,
  PlatformPatchConfigResponses,
  PlatformTriggerDnsCheckData,
  PlatformTriggerDnsCheckErrors,
  PlatformTriggerDnsCheckResponses,
  PlatformUnbanUserData,
  PlatformUnbanUserErrors,
  PlatformUnbanUserResponses,
  PlatformUpdateApplicationData,
  PlatformUpdateApplicationDomainData,
  PlatformUpdateApplicationDomainErrors,
  PlatformUpdateApplicationDomainResponses,
  PlatformUpdateApplicationErrors,
  PlatformUpdateApplicationResponses,
  PlatformUpdateJwtTemplateData,
  PlatformUpdateJwtTemplateErrors,
  PlatformUpdateJwtTemplateResponses,
  PlatformUploadApplicationFaviconData,
  PlatformUploadApplicationFaviconErrors,
  PlatformUploadApplicationFaviconResponses,
  PlatformUploadApplicationLogoData,
  PlatformUploadApplicationLogoErrors,
  PlatformUploadApplicationLogoResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List applications
 *
 * List applications.
 *
 */
export const platformListApplications = <ThrowOnError extends boolean = false>(
  options?: Options<PlatformListApplicationsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    PlatformListApplicationsResponses,
    PlatformListApplicationsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications",
    ...options,
  });

/**
 * Create an application
 *
 * Create a new application.
 *
 */
export const platformCreateApplication = <ThrowOnError extends boolean = false>(
  options: Options<PlatformCreateApplicationData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PlatformCreateApplicationResponses,
    PlatformCreateApplicationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete an application
 *
 * Delete an application.
 *
 */
export const platformDeleteApplication = <ThrowOnError extends boolean = false>(
  options: Options<PlatformDeleteApplicationData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    PlatformDeleteApplicationResponses,
    PlatformDeleteApplicationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}",
    ...options,
  });

/**
 * Get an application
 *
 * Get application details.
 *
 */
export const platformGetApplication = <ThrowOnError extends boolean = false>(
  options: Options<PlatformGetApplicationData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PlatformGetApplicationResponses,
    PlatformGetApplicationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}",
    ...options,
  });

/**
 * Update an application
 *
 * Update an application.
 *
 */
export const platformUpdateApplication = <ThrowOnError extends boolean = false>(
  options: Options<PlatformUpdateApplicationData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    PlatformUpdateApplicationResponses,
    PlatformUpdateApplicationErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete application logo
 *
 * Delete an application's logo.
 *
 */
export const platformDeleteApplicationLogo = <ThrowOnError extends boolean = false>(
  options: Options<PlatformDeleteApplicationLogoData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    PlatformDeleteApplicationLogoResponses,
    PlatformDeleteApplicationLogoErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/logo",
    ...options,
  });

/**
 * Upload application logo
 *
 * Set or replace an application's logo by uploading an image file.
 *
 */
export const platformUploadApplicationLogo = <ThrowOnError extends boolean = false>(
  options: Options<PlatformUploadApplicationLogoData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PlatformUploadApplicationLogoResponses,
    PlatformUploadApplicationLogoErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/logo",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Delete application favicon
 *
 * Delete an application's favicon.
 *
 */
export const platformDeleteApplicationFavicon = <ThrowOnError extends boolean = false>(
  options: Options<PlatformDeleteApplicationFaviconData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    PlatformDeleteApplicationFaviconResponses,
    PlatformDeleteApplicationFaviconErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/favicon",
    ...options,
  });

/**
 * Upload application favicon
 *
 * Set or replace an application's favicon by uploading an image file.
 *
 */
export const platformUploadApplicationFavicon = <ThrowOnError extends boolean = false>(
  options: Options<PlatformUploadApplicationFaviconData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PlatformUploadApplicationFaviconResponses,
    PlatformUploadApplicationFaviconErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/favicon",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Update application domain
 *
 * Update the production domain for an application.
 *
 */
export const platformUpdateApplicationDomain = <ThrowOnError extends boolean = false>(
  options: Options<PlatformUpdateApplicationDomainData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    PlatformUpdateApplicationDomainResponses,
    PlatformUpdateApplicationDomainErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/domain",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List application domains
 *
 * List all domains for an application's production instance.
 *
 */
export const platformListApplicationDomains = <ThrowOnError extends boolean = false>(
  options: Options<PlatformListApplicationDomainsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PlatformListApplicationDomainsResponses,
    PlatformListApplicationDomainsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/domains",
    ...options,
  });

/**
 * Create application domain
 *
 * Create a provider domain for an application's production instance.
 *
 */
export const platformCreateApplicationDomain = <ThrowOnError extends boolean = false>(
  options: Options<PlatformCreateApplicationDomainData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PlatformCreateApplicationDomainResponses,
    PlatformCreateApplicationDomainErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/domains",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete application domain
 *
 * Delete a provider domain from an application's production instance.
 *
 * Only provider domains can be deleted. The primary domain cannot be deleted.
 *
 */
export const platformDeleteApplicationDomain = <ThrowOnError extends boolean = false>(
  options: Options<PlatformDeleteApplicationDomainData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    PlatformDeleteApplicationDomainResponses,
    PlatformDeleteApplicationDomainErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/domains/{domainIDOrName}",
    ...options,
  });

/**
 * Get application domain
 *
 * Get domain information for an application.
 *
 */
export const platformGetApplicationDomain = <ThrowOnError extends boolean = false>(
  options: Options<PlatformGetApplicationDomainData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PlatformGetApplicationDomainResponses,
    PlatformGetApplicationDomainErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/domains/{domainIDOrName}",
    ...options,
  });

/**
 * Get application domain status
 *
 * Get the status of a domain for an application.
 *
 */
export const platformGetApplicationDomainStatus = <ThrowOnError extends boolean = false>(
  options: Options<PlatformGetApplicationDomainStatusData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PlatformGetApplicationDomainStatusResponses,
    PlatformGetApplicationDomainStatusErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/domains/{domainIDOrName}/status",
    ...options,
  });

/**
 * Trigger DNS check
 *
 * Triggers a DNS check for a domain and returns the current domain status.
 *
 * This endpoint ensures that at most one DNS check job is in-flight at any time.
 * If a check is already running or was recently performed, a 409 Conflict is returned.
 *
 * Use this endpoint to trigger a new DNS verification check after configuring DNS records.
 *
 */
export const platformTriggerDnsCheck = <ThrowOnError extends boolean = false>(
  options: Options<PlatformTriggerDnsCheckData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PlatformTriggerDnsCheckResponses,
    PlatformTriggerDnsCheckErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/domains/{domainIDOrName}/dns_check",
    ...options,
  });

/**
 * List application transfers
 *
 * List all transfer requests created by the authenticated workspace. Returns
 * transfers sorted by creation date in descending order (most recent first).
 *
 * Use the `status` parameter to filter by transfer status.
 *
 */
export const platformListApplicationTransfers = <ThrowOnError extends boolean = false>(
  options?: Options<PlatformListApplicationTransfersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    PlatformListApplicationTransfersResponses,
    PlatformListApplicationTransfersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/application_transfers",
    ...options,
  });

/**
 * Create an application transfer
 *
 * Create a new transfer request for an application. This initiates the process of
 * transferring ownership of the application to another workspace.
 *
 * Only one pending transfer can exist for an application at a time. The transfer
 * will expire after 24 hours if not completed.
 *
 */
export const platformCreateApplicationTransfer = <ThrowOnError extends boolean = false>(
  options: Options<PlatformCreateApplicationTransferData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PlatformCreateApplicationTransferResponses,
    PlatformCreateApplicationTransferErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/transfers",
    ...options,
  });

/**
 * Cancel an application transfer
 *
 * Cancel an existing application transfer. Only transfers in 'pending' status can be canceled.
 *
 */
export const platformCancelApplicationTransfer = <ThrowOnError extends boolean = false>(
  options: Options<PlatformCancelApplicationTransferData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    PlatformCancelApplicationTransferResponses,
    PlatformCancelApplicationTransferErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/transfers/{transferID}",
    ...options,
  });

/**
 * Get an application transfer
 *
 * Retrieve details of an application transfer by its ID.
 *
 */
export const platformGetApplicationTransfer = <ThrowOnError extends boolean = false>(
  options: Options<PlatformGetApplicationTransferData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PlatformGetApplicationTransferResponses,
    PlatformGetApplicationTransferErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/transfers/{transferID}",
    ...options,
  });

/**
 * Get instance usage
 *
 * Get usage totals for an application instance across meters such as MAU, MAO,
 * SMS, custom domains, and enterprise connections.
 *
 * The `envOrInsID` parameter can be either an environment type (e.g., "development", "production")
 * or an instance ID.
 *
 * Requires the `application_usage:read` scope.
 *
 */
export const platformGetInstanceUsage = <ThrowOnError extends boolean = false>(
  options: Options<PlatformGetInstanceUsageData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PlatformGetInstanceUsageResponses,
    PlatformGetInstanceUsageErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/usage",
    ...options,
  });

/**
 * List instance users
 *
 * List all users for an application instance.
 *
 * The `envOrInsID` parameter can be either an environment type (e.g., "development", "production")
 * or an instance ID.
 *
 * Use the `query` parameter to filter users by searching across email addresses, phone numbers,
 * usernames, web3 wallets, user IDs, first names, and last names.
 *
 * Use the `order_by` parameter to sort the results. Prefix with `+` for ascending or `-` for descending order.
 * Valid fields: `created_at`, `updated_at`, `last_sign_in_at`, `last_active_at`, `email_address`, `first_name`,
 * `last_name`, `username`, `phone_number`, `web3_wallet`. Default is `-created_at` (most recent first).
 *
 * Requires the `users:read` scope.
 *
 */
export const platformListInstanceUsers = <ThrowOnError extends boolean = false>(
  options: Options<PlatformListInstanceUsersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PlatformListInstanceUsersResponses,
    PlatformListInstanceUsersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/users",
    ...options,
  });

/**
 * Ban a user
 *
 * Marks a user as banned within an application instance. This terminates their active sessions
 * (marks them as revoked) and prevents them from signing in again.
 *
 * Requires the `users:manage` scope.
 *
 */
export const platformBanUser = <ThrowOnError extends boolean = false>(
  options: Options<PlatformBanUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<PlatformBanUserResponses, PlatformBanUserErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/users/{userID}/ban",
    ...options,
  });

/**
 * Unban a user
 *
 * Removes the ban from a user within an application instance. This allows them to sign in again.
 *
 * Requires the `users:manage` scope.
 *
 */
export const platformUnbanUser = <ThrowOnError extends boolean = false>(
  options: Options<PlatformUnbanUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PlatformUnbanUserResponses,
    PlatformUnbanUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/users/{userID}/unban",
    ...options,
  });

/**
 * List JWT templates
 *
 * List all JWT templates for an application instance.
 *
 * Requires the `jwt_templates:read` scope.
 *
 */
export const platformListJwtTemplates = <ThrowOnError extends boolean = false>(
  options: Options<PlatformListJwtTemplatesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PlatformListJwtTemplatesResponses,
    PlatformListJwtTemplatesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/jwt_templates",
    ...options,
  });

/**
 * Create a JWT template
 *
 * Create a new JWT template for an application instance.
 *
 * Requires the `jwt_templates:manage` scope.
 *
 */
export const platformCreateJwtTemplate = <ThrowOnError extends boolean = false>(
  options: Options<PlatformCreateJwtTemplateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PlatformCreateJwtTemplateResponses,
    PlatformCreateJwtTemplateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/jwt_templates",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a JWT template
 *
 * Delete a JWT template from an application instance.
 *
 * Requires the `jwt_templates:manage` scope.
 *
 */
export const platformDeleteJwtTemplate = <ThrowOnError extends boolean = false>(
  options: Options<PlatformDeleteJwtTemplateData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    PlatformDeleteJwtTemplateResponses,
    PlatformDeleteJwtTemplateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/jwt_templates/{templateID}",
    ...options,
  });

/**
 * Get a JWT template
 *
 * Retrieve a specific JWT template for an application instance.
 *
 * Requires the `jwt_templates:read` scope.
 *
 */
export const platformGetJwtTemplate = <ThrowOnError extends boolean = false>(
  options: Options<PlatformGetJwtTemplateData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PlatformGetJwtTemplateResponses,
    PlatformGetJwtTemplateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/jwt_templates/{templateID}",
    ...options,
  });

/**
 * Update a JWT template
 *
 * Update an existing JWT template for an application instance.
 *
 * Requires the `jwt_templates:manage` scope.
 *
 */
export const platformUpdateJwtTemplate = <ThrowOnError extends boolean = false>(
  options: Options<PlatformUpdateJwtTemplateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    PlatformUpdateJwtTemplateResponses,
    PlatformUpdateJwtTemplateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/jwt_templates/{templateID}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List redirect URLs
 *
 * List all redirect URLs for an application instance.
 *
 * The `envOrInsID` parameter can be either an environment type (e.g., "development", "production")
 * or an instance ID.
 *
 * Requires the `applications:read` scope.
 *
 */
export const platformListRedirectUrls = <ThrowOnError extends boolean = false>(
  options: Options<PlatformListRedirectUrlsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PlatformListRedirectUrlsResponses,
    PlatformListRedirectUrlsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/redirect_urls",
    ...options,
  });

/**
 * Create a redirect URL
 *
 * Create a redirect URL for an application instance.
 *
 * The `envOrInsID` parameter can be either an environment type (e.g., "development", "production")
 * or an instance ID.
 *
 * Requires the `applications:manage` scope.
 *
 */
export const platformCreateRedirectUrl = <ThrowOnError extends boolean = false>(
  options: Options<PlatformCreateRedirectUrlData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PlatformCreateRedirectUrlResponses,
    PlatformCreateRedirectUrlErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/redirect_urls",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a redirect URL
 *
 * Delete a redirect URL from an application instance.
 *
 * The `envOrInsID` parameter can be either an environment type (e.g., "development", "production")
 * or an instance ID.
 *
 * Requires the `applications:manage` scope.
 *
 */
export const platformDeleteRedirectUrl = <ThrowOnError extends boolean = false>(
  options: Options<PlatformDeleteRedirectUrlData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    PlatformDeleteRedirectUrlResponses,
    PlatformDeleteRedirectUrlErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/redirect_urls/{redirectURLID}",
    ...options,
  });

/**
 * Get a redirect URL
 *
 * Retrieve a redirect URL for an application instance.
 *
 * The `envOrInsID` parameter can be either an environment type (e.g., "development", "production")
 * or an instance ID.
 *
 * Requires the `applications:read` scope.
 *
 */
export const platformGetRedirectUrl = <ThrowOnError extends boolean = false>(
  options: Options<PlatformGetRedirectUrlData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PlatformGetRedirectUrlResponses,
    PlatformGetRedirectUrlErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/redirect_urls/{redirectURLID}",
    ...options,
  });

/**
 * Get instance config
 *
 * Get the configuration for an application instance.
 *
 * The `envOrInsID` parameter can be either an environment type (e.g., "development", "production")
 * or an instance ID.
 *
 * Optionally filter to specific config keys using the `keys` query parameter.
 *
 * Requires the `applications:manage` scope.
 *
 */
export const platformGetConfig = <ThrowOnError extends boolean = false>(
  options: Options<PlatformGetConfigData, ThrowOnError>,
) =>
  (options.client ?? client).get<PlatformGetConfigResponses, PlatformGetConfigErrors, ThrowOnError>(
    {
      security: [{ scheme: "bearer", type: "http" }],
      url: "/platform/applications/{applicationID}/instances/{envOrInsID}/config",
      ...options,
    },
  );

/**
 * Update instance config
 *
 * Update the configuration for an application instance.
 *
 * The `envOrInsID` parameter can be either an environment type (e.g., "development", "production")
 * or an instance ID.
 *
 * Use the `dry_run` query parameter to preview changes without applying them.
 * Use the `destructive` query parameter to allow clearing config keys by setting them to null.
 * Use the `If-Match` header to provide optimistic concurrency control via config version.
 *
 * Requires the `applications:manage` scope.
 *
 */
export const platformPatchConfig = <ThrowOnError extends boolean = false>(
  options: Options<PlatformPatchConfigData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    PlatformPatchConfigResponses,
    PlatformPatchConfigErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/config",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get instance config schema
 *
 * Get the JSON Schema for the instance configuration.
 *
 * The `envOrInsID` parameter can be either an environment type (e.g., "development", "production")
 * or an instance ID.
 *
 * Optionally filter to specific config keys using the `keys` query parameter.
 *
 * Requires the `applications:manage` scope.
 *
 */
export const platformGetConfigSchema = <ThrowOnError extends boolean = false>(
  options: Options<PlatformGetConfigSchemaData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    PlatformGetConfigSchemaResponses,
    PlatformGetConfigSchemaErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/platform/applications/{applicationID}/instances/{envOrInsID}/config/schema",
    ...options,
  });
