// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.clerk.com/v1' | (string & {});
};

/**
 * Application Instance
 *
 * Represents an instance (environment) within a Clerk application. Each application can have multiple instances, typically one for development and one for production.
 */
export type PlatformApplicationInstance = {
    /**
     * The unique identifier for this instance. Use this ID when making API calls that target a specific instance.
     */
    instance_id: string;
    /**
     * The environment type of the instance. Determines whether this instance is used for development/testing or production workloads.
     */
    environment_type: 'development' | 'production';
    /**
     * The secret key for authenticating server-side API requests to this instance. Keep this value secure and never expose it in client-side code.
     */
    secret_key?: string;
    /**
     * The publishable key for this instance. Safe to include in client-side code and used to initialize Clerk SDKs in the browser.
     */
    publishable_key: string;
};

export type PlatformApplicationResponse = {
    /**
     * The ID of the application.
     */
    application_id: string;
    /**
     * List of instances associated with this application.
     */
    instances: Array<PlatformApplicationInstance>;
};

export type PlatformListApplicationsResponse = Array<PlatformApplicationResponse>;

export type ClerkError = {
    message: string;
    long_message: string;
    code: string;
    meta?: {
        [key: string]: unknown;
    };
};

export type ClerkErrors = {
    errors: Array<ClerkError>;
    meta?: {
        [key: string]: unknown;
    };
    clerk_trace_id?: string;
};

export type PlatformCreateApplicationRequest = {
    /**
     * The name of the application.
     */
    name: string;
    /**
     * The domain for the application (optional).
     */
    domain?: string;
    /**
     * List of environment types to create instances for.
     */
    environment_types?: Array<'development' | 'production'>;
    /**
     * Application template to use for configuring the application (e.g., "b2b-saas", "b2c-saas", "waitlist").
     */
    template?: string;
};

export type PlatformDeletedObjectResponse = {
    /**
     * Whether the object was deleted.
     */
    deleted: boolean;
    object: string;
    /**
     * The ID of the deleted resource.
     */
    id: string;
};

export type PlatformUpdateApplicationRequest = {
    /**
     * The name of the application.
     */
    name?: string;
};

export type PlatformUpdateApplicationDomainRequest = {
    /**
     * The domain name.
     */
    name: string;
};

export type PlatformDomainResponse = {
    object: 'domain';
    /**
     * The ID of the domain.
     */
    id: string;
    /**
     * The domain name.
     */
    name: string;
    /**
     * Whether this is a satellite domain.
     */
    is_satellite?: boolean;
    /**
     * The frontend API URL.
     */
    frontend_api_url: string;
    /**
     * The development origin.
     */
    development_origin: string;
    /**
     * The accounts portal URL.
     */
    accounts_portal_url: string;
    /**
     * CNAME targets for the domain.
     */
    cname_targets: Array<{
        name?: string;
        value?: string;
        required?: boolean;
    }>;
};

export type FailureHint = {
    code: string;
    message: string;
};

export type CnameStatus = {
    clerk_subdomain: string;
    from: string;
    to: string;
    verified: boolean;
    required: boolean;
    failure_hints: Array<FailureHint>;
};

export type DnsStatus = {
    status: 'not_started' | 'in_progress' | 'complete';
    cnames: {
        accounts?: CnameStatus;
        clerk?: CnameStatus;
        'clk._domainkey'?: CnameStatus;
        'clk2._domainkey'?: CnameStatus;
        clkmail?: CnameStatus;
    };
};

export type SslStatus = {
    status: string;
    required: boolean;
    failure_hints: Array<FailureHint> | null;
};

export type PlatformDomainStatusResponse = {
    dns: DnsStatus;
    ssl: {
        status?: 'complete' | 'in_process' | 'not_started' | 'failed' | 'incomplete';
        required?: boolean;
        failure_hints?: Array<FailureHint> | null;
    };
    ssl_hosts?: {
        [key: string]: SslStatus;
    };
    mail?: {
        status: string;
        required: boolean;
    };
    proxy?: {
        status: string;
        required: boolean;
    };
    status: 'complete' | 'incomplete';
};

/**
 * Response from triggering a DNS check. Includes the current domain status
 * along with metadata about the check.
 *
 */
export type PlatformDnsCheckResponse = PlatformDomainStatusResponse & {
    /**
     * The ID of the domain.
     */
    domain_id: string;
    /**
     * The timestamp in epoch milliseconds of the last DNS check, if any.
     * Will be `null` if no check has been performed yet.
     *
     */
    last_run_at: number | null;
};

export type PlatformListApplicationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Whether to include secret keys in the response.
         */
        include_secret_keys?: boolean;
    };
    url: '/platform/applications';
};

export type PlatformListApplicationsErrors = {
    /**
     * Request was not successful
     */
    400: ClerkErrors;
    /**
     * Authentication invalid
     */
    401: ClerkErrors;
    /**
     * Authorization invalid
     */
    403: ClerkErrors;
};

export type PlatformListApplicationsError = PlatformListApplicationsErrors[keyof PlatformListApplicationsErrors];

export type PlatformListApplicationsResponses = {
    /**
     * Applications retrieved successfully.
     */
    200: PlatformListApplicationsResponse;
};

export type PlatformListApplicationsResponse2 = PlatformListApplicationsResponses[keyof PlatformListApplicationsResponses];

export type PlatformCreateApplicationData = {
    /**
     * Application data to create.
     */
    body: PlatformCreateApplicationRequest;
    path?: never;
    query?: never;
    url: '/platform/applications';
};

export type PlatformCreateApplicationErrors = {
    /**
     * Request was not successful
     */
    400: ClerkErrors;
    /**
     * Authentication invalid
     */
    401: ClerkErrors;
    /**
     * Authorization invalid
     */
    403: ClerkErrors;
    /**
     * Invalid request parameters
     */
    422: ClerkErrors;
};

export type PlatformCreateApplicationError = PlatformCreateApplicationErrors[keyof PlatformCreateApplicationErrors];

export type PlatformCreateApplicationResponses = {
    /**
     * Application created successfully.
     */
    200: PlatformApplicationResponse;
};

export type PlatformCreateApplicationResponse = PlatformCreateApplicationResponses[keyof PlatformCreateApplicationResponses];

export type PlatformDeleteApplicationData = {
    body?: never;
    path: {
        /**
         * Application ID.
         */
        applicationID: string;
    };
    query?: never;
    url: '/platform/applications/{applicationID}';
};

export type PlatformDeleteApplicationErrors = {
    /**
     * Request was not successful
     */
    400: ClerkErrors;
    /**
     * Authentication invalid
     */
    401: ClerkErrors;
    /**
     * Authorization invalid
     */
    403: ClerkErrors;
    /**
     * Resource not found
     */
    404: ClerkErrors;
};

export type PlatformDeleteApplicationError = PlatformDeleteApplicationErrors[keyof PlatformDeleteApplicationErrors];

export type PlatformDeleteApplicationResponses = {
    /**
     * Application deleted successfully.
     */
    200: PlatformDeletedObjectResponse;
};

export type PlatformDeleteApplicationResponse = PlatformDeleteApplicationResponses[keyof PlatformDeleteApplicationResponses];

export type PlatformGetApplicationData = {
    body?: never;
    path: {
        /**
         * Application ID.
         */
        applicationID: string;
    };
    query?: {
        /**
         * Whether to include secret keys in the response. If 'true', the response will include the secret keys for each instance.
         */
        include_secret_keys?: boolean;
    };
    url: '/platform/applications/{applicationID}';
};

export type PlatformGetApplicationErrors = {
    /**
     * Request was not successful
     */
    400: ClerkErrors;
    /**
     * Authentication invalid
     */
    401: ClerkErrors;
    /**
     * Authorization invalid
     */
    403: ClerkErrors;
    /**
     * Resource not found
     */
    404: ClerkErrors;
};

export type PlatformGetApplicationError = PlatformGetApplicationErrors[keyof PlatformGetApplicationErrors];

export type PlatformGetApplicationResponses = {
    /**
     * Application retrieved successfully.
     */
    200: PlatformApplicationResponse;
};

export type PlatformGetApplicationResponse = PlatformGetApplicationResponses[keyof PlatformGetApplicationResponses];

export type PlatformUpdateApplicationData = {
    /**
     * Application data to update.
     */
    body: PlatformUpdateApplicationRequest;
    path: {
        /**
         * Application ID.
         */
        applicationID: string;
    };
    query?: never;
    url: '/platform/applications/{applicationID}';
};

export type PlatformUpdateApplicationErrors = {
    /**
     * Request was not successful
     */
    400: ClerkErrors;
    /**
     * Authentication invalid
     */
    401: ClerkErrors;
    /**
     * Authorization invalid
     */
    403: ClerkErrors;
    /**
     * Resource not found
     */
    404: ClerkErrors;
    /**
     * Invalid request parameters
     */
    422: ClerkErrors;
};

export type PlatformUpdateApplicationError = PlatformUpdateApplicationErrors[keyof PlatformUpdateApplicationErrors];

export type PlatformUpdateApplicationResponses = {
    /**
     * Application updated successfully.
     */
    200: PlatformApplicationResponse;
};

export type PlatformUpdateApplicationResponse = PlatformUpdateApplicationResponses[keyof PlatformUpdateApplicationResponses];

export type PlatformUpdateApplicationDomainData = {
    /**
     * Domain data to update.
     */
    body: PlatformUpdateApplicationDomainRequest;
    path: {
        /**
         * Application ID.
         */
        applicationID: string;
    };
    query?: never;
    url: '/platform/applications/{applicationID}/domain';
};

export type PlatformUpdateApplicationDomainErrors = {
    /**
     * Request was not successful
     */
    400: ClerkErrors;
    /**
     * Authentication invalid
     */
    401: ClerkErrors;
    /**
     * Authorization invalid
     */
    403: ClerkErrors;
    /**
     * Resource not found
     */
    404: ClerkErrors;
    /**
     * Invalid request parameters
     */
    422: ClerkErrors;
};

export type PlatformUpdateApplicationDomainError = PlatformUpdateApplicationDomainErrors[keyof PlatformUpdateApplicationDomainErrors];

export type PlatformUpdateApplicationDomainResponses = {
    /**
     * Application domain updated successfully.
     */
    200: PlatformDomainResponse;
};

export type PlatformUpdateApplicationDomainResponse = PlatformUpdateApplicationDomainResponses[keyof PlatformUpdateApplicationDomainResponses];

export type PlatformGetApplicationDomainData = {
    body?: never;
    path: {
        /**
         * Application ID.
         */
        applicationID: string;
        /**
         * Domain ID or domain name.
         */
        domainIDOrName: string;
    };
    query?: never;
    url: '/platform/applications/{applicationID}/domains/{domainIDOrName}';
};

export type PlatformGetApplicationDomainErrors = {
    /**
     * Request was not successful
     */
    400: ClerkErrors;
    /**
     * Authentication invalid
     */
    401: ClerkErrors;
    /**
     * Authorization invalid
     */
    403: ClerkErrors;
    /**
     * Resource not found
     */
    404: ClerkErrors;
};

export type PlatformGetApplicationDomainError = PlatformGetApplicationDomainErrors[keyof PlatformGetApplicationDomainErrors];

export type PlatformGetApplicationDomainResponses = {
    /**
     * Application domain retrieved successfully.
     */
    200: PlatformDomainResponse;
};

export type PlatformGetApplicationDomainResponse = PlatformGetApplicationDomainResponses[keyof PlatformGetApplicationDomainResponses];

export type PlatformGetApplicationDomainStatusData = {
    body?: never;
    path: {
        /**
         * Application ID.
         */
        applicationID: string;
        /**
         * Domain ID or domain name.
         */
        domainIDOrName: string;
    };
    query?: never;
    url: '/platform/applications/{applicationID}/domains/{domainIDOrName}/status';
};

export type PlatformGetApplicationDomainStatusErrors = {
    /**
     * Request was not successful
     */
    400: ClerkErrors;
    /**
     * Authentication invalid
     */
    401: ClerkErrors;
    /**
     * Authorization invalid
     */
    403: ClerkErrors;
    /**
     * Resource not found
     */
    404: ClerkErrors;
};

export type PlatformGetApplicationDomainStatusError = PlatformGetApplicationDomainStatusErrors[keyof PlatformGetApplicationDomainStatusErrors];

export type PlatformGetApplicationDomainStatusResponses = {
    /**
     * Application domain status retrieved successfully.
     */
    200: PlatformDomainStatusResponse;
};

export type PlatformGetApplicationDomainStatusResponse = PlatformGetApplicationDomainStatusResponses[keyof PlatformGetApplicationDomainStatusResponses];

export type PlatformTriggerDnsCheckData = {
    body?: never;
    path: {
        /**
         * Application ID.
         */
        applicationID: string;
        /**
         * Domain ID or domain name.
         */
        domainIDOrName: string;
    };
    query?: never;
    url: '/platform/applications/{applicationID}/domains/{domainIDOrName}/dns_check';
};

export type PlatformTriggerDnsCheckErrors = {
    /**
     * Request was not successful
     */
    400: ClerkErrors;
    /**
     * Authentication invalid
     */
    401: ClerkErrors;
    /**
     * Authorization invalid
     */
    403: ClerkErrors;
    /**
     * Resource not found
     */
    404: ClerkErrors;
    /**
     * Conflict
     */
    409: ClerkErrors;
};

export type PlatformTriggerDnsCheckError = PlatformTriggerDnsCheckErrors[keyof PlatformTriggerDnsCheckErrors];

export type PlatformTriggerDnsCheckResponses = {
    /**
     * DNS check triggered and domain status returned successfully.
     */
    200: PlatformDnsCheckResponse;
};

export type PlatformTriggerDnsCheckResponse = PlatformTriggerDnsCheckResponses[keyof PlatformTriggerDnsCheckResponses];
