import { NextResponse } from "next/server";
import z from "zod";

import { db } from "@/lib/database/db";
import { Message, UpdateMessageInput } from "@/lib/models/message";
import { createMessageRepository } from "@/lib/repositories/message-repository-impl";

const ParamsSchema = z.object({
  chatId: z.string().uuid(),
  // Message ids are generated by the AI SDK and may not be UUIDs.
  messageId: z.string().min(1),
});

export interface UpdateMessageBody {
  message: UpdateMessageInput;
}

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ chatId: string; messageId: string }> },
) {
  const { chatId, messageId } = await params;
  const parsedParams = ParamsSchema.safeParse({ chatId, messageId });
  if (!parsedParams.success) {
    return NextResponse.json({ error: "Invalid parameters" }, { status: 400 });
  }

  const messageRepo = createMessageRepository(db);
  const row = await messageRepo.getById(parsedParams.data.messageId);
  if (!row || row.conversationId !== parsedParams.data.chatId) {
    return NextResponse.json({ error: "Message not found" }, { status: 404 });
  }

  return NextResponse.json<GETResponse>({ message: row }, { status: 200 });
}

export async function PATCH(
  req: Request,
  { params }: { params: Promise<{ chatId: string; messageId: string }> },
) {
  const { chatId, messageId } = await params;
  const parsedParams = ParamsSchema.safeParse({ chatId, messageId });
  if (!parsedParams.success) {
    return NextResponse.json({ error: "Invalid parameters" }, { status: 400 });
  }

  const body = (await req.json().catch(() => null)) as UpdateMessageBody | null;
  if (!body) {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  const messageRepo = createMessageRepository(db);
  const existing = await messageRepo.getById(parsedParams.data.messageId);
  if (!existing || existing.conversationId !== parsedParams.data.chatId) {
    return NextResponse.json({ error: "Message not found" }, { status: 404 });
  }

  const updated = await messageRepo.update(parsedParams.data.messageId, {
    metadata: body.message.metadata,
    parts: body.message.parts,
  });
  if (!updated) {
    return NextResponse.json({ error: "Message not found" }, { status: 404 });
  }

  return NextResponse.json<PATCHResponse>({ message: updated }, { status: 200 });
}

export async function DELETE(
  _req: Request,
  { params }: { params: Promise<{ chatId: string; messageId: string }> },
) {
  const { chatId, messageId } = await params;
  const parsedParams = ParamsSchema.safeParse({ chatId, messageId });
  if (!parsedParams.success) {
    return NextResponse.json({ error: "Invalid parameters" }, { status: 400 });
  }

  const messageRepo = createMessageRepository(db);
  const existing = await messageRepo.getById(parsedParams.data.messageId);
  if (!existing || existing.conversationId !== parsedParams.data.chatId) {
    return NextResponse.json({ error: "Message not found" }, { status: 404 });
  }

  await messageRepo.delete(parsedParams.data.messageId);

  return NextResponse.json<DELETEResponse>({ deleted: true }, { status: 200 });
}

export interface GETResponse {
  message: Message;
}

export interface PATCHResponse {
  message: Message;
}

export interface DELETEResponse {
  deleted: true;
}
